# Generated by Django 6.0 on 2025-12-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('hr', 'HR'), ('admin', 'Admin')], default='hr', max_length=10),
        ),
    ]
