# Generated by Django 5.2.9 on 2025-12-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_employee_options_employee_is_remote_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employee_code']},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_remote',
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='employees/'),
        ),
    ]
