# Generated by Django 5.2.9 on 2025-12-16 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_employee_options_remove_employee_is_remote_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
    ]
