# Generated by Django 5.2.9 on 2025-12-24 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employee',
            name='annual_ctc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employee',
            name='basic_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employee',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full Time'), ('TEMPORARY', 'Temporary')], default='FULL_TIME', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='probation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportees', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_shift',
            field=models.CharField(choices=[('DAY', 'Day Shift'), ('NIGHT', 'Night Shift'), ('ROTATIONAL', 'Rotational Shift')], default='DAY', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_timing',
            field=models.CharField(default='09:00 AM - 06:00 PM', max_length=50),
        ),
        migrations.CreateModel(
            name='EmployeeOffboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resignation_date', models.DateField()),
                ('last_working_date', models.DateField()),
                ('reason_for_exit', models.CharField(max_length=255)),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offboarding', to='accounts.employee')),
            ],
        ),
        migrations.CreateModel(
            name='OffboardingChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('LAPTOP_RETURNED', 'Laptop Returned'), ('ACCESS_CARD', 'Access Card Returned'), ('DOCUMENTS', 'Documents Submitted'), ('NO_DUES', 'No Dues Clearance'), ('KNOWLEDGE_TRANSFER', 'Knowledge Transfer Completed')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted')], default='PENDING', max_length=20)),
                ('offboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='accounts.employeeoffboarding')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('RESUME', 'Resume'), ('ID_PROOF', 'ID Proof'), ('OFFER_LETTER', 'Offer Letter'), ('EXPERIENCE', 'Experience Letter')], max_length=50)),
                ('file', models.FileField(upload_to='employee_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.employee')),
            ],
            options={
                'unique_together': {('employee', 'document_type')},
            },
        ),
    ]
